platform :mac do
  lane :release do
    increment_build_number(build_number: 3)
    build_app(catalyst_platform: "macos", installer_cert_name: "3rd Party Mac Developer Installer: Morten Gregersen (R7YA4RGA8U)")
    upload_to_app_store
  end
end

platform :ios do
  lane :release do
    increment_build_number(build_number: number_of_commits)
    build_app(catalyst_platform: "ios")
    upload_to_app_store
  end
end
